name: Deploy Simple CI/CD

on:
  push:
    branches: ["feature/add-docker"]

# env:
#   AWS_REGION: ap-northeast-1
#   ECS_SERVICE: simple-cicd-service
#   ECS_CLUSTER: simple-cicd-cluster
#   ECS_TASK_DEFINITION: .aws/task-definition.json

# permissions:
#   contents: read

jobs:
  app-test-build-image:
    name: App Container - Test and Build
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    # defaults:
    #   run:
    #     working-directory: app

    steps:
      - name: test steps
        run: echo "Hello world"

      - name: checkoutcode
        uses: actions/checkout@v3

      - name: check current directory
        run: ls -al

      # - name: build container
      #   run: docker build -t chatspace-app:v0.0.1 .


    #   - name: Build an Image and Run Tests
    #     run: |
    #       docker image build --target production -t temp_app_image_name:latest --build-arg APP
